/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.JOURNAL
	 */
	public static final com.intechua.db.jooq.tables.Journal JOURNAL = com.intechua.db.jooq.tables.Journal.JOURNAL;

	/**
	 * The table PUBLIC.OPERATOR
	 */
	public static final com.intechua.db.jooq.tables.Operator OPERATOR = com.intechua.db.jooq.tables.Operator.OPERATOR;

	/**
	 * The table PUBLIC.PACKETS
	 */
	public static final com.intechua.db.jooq.tables.Packets PACKETS = com.intechua.db.jooq.tables.Packets.PACKETS;

	/**
	 * The table PUBLIC.SETTINGS
	 */
	public static final com.intechua.db.jooq.tables.Settings SETTINGS = com.intechua.db.jooq.tables.Settings.SETTINGS;
}
