/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Journal extends org.jooq.impl.TableImpl<com.intechua.db.jooq.tables.records.JournalRecord> {

	private static final long serialVersionUID = -85869749;

	/**
	 * The singleton instance of <code>PUBLIC.JOURNAL</code>
	 */
	public static final com.intechua.db.jooq.tables.Journal JOURNAL = new com.intechua.db.jooq.tables.Journal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.intechua.db.jooq.tables.records.JournalRecord> getRecordType() {
		return com.intechua.db.jooq.tables.records.JournalRecord.class;
	}

	/**
	 * The column <code>PUBLIC.JOURNAL.ID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.DATE</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.sql.Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.COUNTER_ID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> COUNTER_ID = createField("COUNTER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.LEVEL</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> LEVEL = createField("LEVEL", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.RAWLEVEL</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> RAWLEVEL = createField("RAWLEVEL", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.STATE</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.JOURNAL.POWER</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> POWER = createField("POWER", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>PUBLIC.JOURNAL</code> table reference
	 */
	public Journal() {
		this("JOURNAL", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.JOURNAL</code> table reference
	 */
	public Journal(java.lang.String alias) {
		this(alias, com.intechua.db.jooq.tables.Journal.JOURNAL);
	}

	private Journal(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.JournalRecord> aliased) {
		this(alias, aliased, null);
	}

	private Journal(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.JournalRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.intechua.db.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.intechua.db.jooq.tables.records.JournalRecord, java.lang.Integer> getIdentity() {
		return com.intechua.db.jooq.Keys.IDENTITY_JOURNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.JournalRecord> getPrimaryKey() {
		return com.intechua.db.jooq.Keys.SYS_PK_10100;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.JournalRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.JournalRecord>>asList(com.intechua.db.jooq.Keys.SYS_PK_10100);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.intechua.db.jooq.tables.Journal as(java.lang.String alias) {
		return new com.intechua.db.jooq.tables.Journal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.intechua.db.jooq.tables.Journal rename(java.lang.String name) {
		return new com.intechua.db.jooq.tables.Journal(name, null);
	}
}
