/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Packets extends org.jooq.impl.TableImpl<com.intechua.db.jooq.tables.records.PacketsRecord> {

	private static final long serialVersionUID = 1322614630;

	/**
	 * The singleton instance of <code>PUBLIC.PACKETS</code>
	 */
	public static final com.intechua.db.jooq.tables.Packets PACKETS = new com.intechua.db.jooq.tables.Packets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.intechua.db.jooq.tables.records.PacketsRecord> getRecordType() {
		return com.intechua.db.jooq.tables.records.PacketsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.PACKETS.ID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.DATE</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.sql.Timestamp> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.MODEMID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> MODEMID = createField("MODEMID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.LEVEL1</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> LEVEL1 = createField("LEVEL1", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.LEVEL2</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> LEVEL2 = createField("LEVEL2", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.LEVEL3</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> LEVEL3 = createField("LEVEL3", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.RAWLEVEL1</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> RAWLEVEL1 = createField("RAWLEVEL1", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.RAWLEVEL2</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> RAWLEVEL2 = createField("RAWLEVEL2", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.RAWLEVEL3</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> RAWLEVEL3 = createField("RAWLEVEL3", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.STATE</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.PACKETS.CONNECTION_LEVEL</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> CONNECTION_LEVEL = createField("CONNECTION_LEVEL", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>PUBLIC.PACKETS</code> table reference
	 */
	public Packets() {
		this("PACKETS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.PACKETS</code> table reference
	 */
	public Packets(java.lang.String alias) {
		this(alias, com.intechua.db.jooq.tables.Packets.PACKETS);
	}

	private Packets(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.PacketsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Packets(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.PacketsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.intechua.db.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.intechua.db.jooq.tables.records.PacketsRecord, java.lang.Integer> getIdentity() {
		return com.intechua.db.jooq.Keys.IDENTITY_PACKETS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.PacketsRecord> getPrimaryKey() {
		return com.intechua.db.jooq.Keys.SYS_PK_10097;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.PacketsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.PacketsRecord>>asList(com.intechua.db.jooq.Keys.SYS_PK_10097);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.intechua.db.jooq.tables.Packets as(java.lang.String alias) {
		return new com.intechua.db.jooq.tables.Packets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.intechua.db.jooq.tables.Packets rename(java.lang.String name) {
		return new com.intechua.db.jooq.tables.Packets(name, null);
	}
}
