/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleTable extends org.jooq.impl.TableImpl<com.intechua.db.jooq.tables.records.SampleTableRecord> {

	private static final long serialVersionUID = 2129110684;

	/**
	 * The singleton instance of <code>PUBLIC.SAMPLE_TABLE</code>
	 */
	public static final com.intechua.db.jooq.tables.SampleTable SAMPLE_TABLE = new com.intechua.db.jooq.tables.SampleTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.intechua.db.jooq.tables.records.SampleTableRecord> getRecordType() {
		return com.intechua.db.jooq.tables.records.SampleTableRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SAMPLE_TABLE.ID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SampleTableRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SAMPLE_TABLE.STR_COL</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SampleTableRecord, java.lang.String> STR_COL = createField("STR_COL", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>PUBLIC.SAMPLE_TABLE.NUM_COL</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SampleTableRecord, java.lang.Integer> NUM_COL = createField("NUM_COL", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>PUBLIC.SAMPLE_TABLE</code> table reference
	 */
	public SampleTable() {
		this("SAMPLE_TABLE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.SAMPLE_TABLE</code> table reference
	 */
	public SampleTable(java.lang.String alias) {
		this(alias, com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE);
	}

	private SampleTable(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.SampleTableRecord> aliased) {
		this(alias, aliased, null);
	}

	private SampleTable(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.SampleTableRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.intechua.db.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.intechua.db.jooq.tables.records.SampleTableRecord, java.lang.Integer> getIdentity() {
		return com.intechua.db.jooq.Keys.IDENTITY_SAMPLE_TABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SampleTableRecord> getPrimaryKey() {
		return com.intechua.db.jooq.Keys.SYS_PK_10092;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SampleTableRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SampleTableRecord>>asList(com.intechua.db.jooq.Keys.SYS_PK_10092);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.intechua.db.jooq.tables.SampleTable as(java.lang.String alias) {
		return new com.intechua.db.jooq.tables.SampleTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.intechua.db.jooq.tables.SampleTable rename(java.lang.String name) {
		return new com.intechua.db.jooq.tables.SampleTable(name, null);
	}
}
