/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleTableRecord extends org.jooq.impl.UpdatableRecordImpl<com.intechua.db.jooq.tables.records.SampleTableRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 865702471;

	/**
	 * Setter for <code>PUBLIC.SAMPLE_TABLE.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.SAMPLE_TABLE.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.SAMPLE_TABLE.STR_COL</code>.
	 */
	public void setStrCol(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.SAMPLE_TABLE.STR_COL</code>.
	 */
	public java.lang.String getStrCol() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.SAMPLE_TABLE.NUM_COL</code>.
	 */
	public void setNumCol(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.SAMPLE_TABLE.NUM_COL</code>.
	 */
	public java.lang.Integer getNumCol() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE.STR_COL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE.NUM_COL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStrCol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getNumCol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SampleTableRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SampleTableRecord value2(java.lang.String value) {
		setStrCol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SampleTableRecord value3(java.lang.Integer value) {
		setNumCol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SampleTableRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SampleTableRecord
	 */
	public SampleTableRecord() {
		super(com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE);
	}

	/**
	 * Create a detached, initialised SampleTableRecord
	 */
	public SampleTableRecord(java.lang.Integer id, java.lang.String strCol, java.lang.Integer numCol) {
		super(com.intechua.db.jooq.tables.SampleTable.SAMPLE_TABLE);

		setValue(0, id);
		setValue(1, strCol);
		setValue(2, numCol);
	}
}
