/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends org.jooq.impl.TableImpl<com.intechua.db.jooq.tables.records.SettingsRecord> {

	private static final long serialVersionUID = -1005201724;

	/**
	 * The singleton instance of <code>PUBLIC.SETTINGS</code>
	 */
	public static final com.intechua.db.jooq.tables.Settings SETTINGS = new com.intechua.db.jooq.tables.Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.intechua.db.jooq.tables.records.SettingsRecord> getRecordType() {
		return com.intechua.db.jooq.tables.records.SettingsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SETTINGS.ID</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SettingsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SETTINGS.NAME</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SettingsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>PUBLIC.SETTINGS.DESC</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SettingsRecord, java.lang.String> DESC = createField("DESC", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>PUBLIC.SETTINGS.VALUE</code>.
	 */
	public final org.jooq.TableField<com.intechua.db.jooq.tables.records.SettingsRecord, java.lang.String> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * Create a <code>PUBLIC.SETTINGS</code> table reference
	 */
	public Settings() {
		this("SETTINGS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.SETTINGS</code> table reference
	 */
	public Settings(java.lang.String alias) {
		this(alias, com.intechua.db.jooq.tables.Settings.SETTINGS);
	}

	private Settings(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.SettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settings(java.lang.String alias, org.jooq.Table<com.intechua.db.jooq.tables.records.SettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.intechua.db.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.intechua.db.jooq.tables.records.SettingsRecord, java.lang.Integer> getIdentity() {
		return com.intechua.db.jooq.Keys.IDENTITY_SETTINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SettingsRecord> getPrimaryKey() {
		return com.intechua.db.jooq.Keys.SYS_PK_10096;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.intechua.db.jooq.tables.records.SettingsRecord>>asList(com.intechua.db.jooq.Keys.SYS_PK_10096);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.intechua.db.jooq.tables.Settings as(java.lang.String alias) {
		return new com.intechua.db.jooq.tables.Settings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.intechua.db.jooq.tables.Settings rename(java.lang.String name) {
		return new com.intechua.db.jooq.tables.Settings(name, null);
	}
}
