/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JournalRecord extends org.jooq.impl.UpdatableRecordImpl<com.intechua.db.jooq.tables.records.JournalRecord> implements org.jooq.Record6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 362831359;

	/**
	 * Setter for <code>PUBLIC.JOURNAL.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.JOURNAL.DATE</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.DATE</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.JOURNAL.COUNTER_ID</code>.
	 */
	public void setCounterId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.COUNTER_ID</code>.
	 */
	public java.lang.Integer getCounterId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.JOURNAL.LEVEL</code>.
	 */
	public void setLevel(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.LEVEL</code>.
	 */
	public java.lang.Integer getLevel() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.JOURNAL.STATE</code>.
	 */
	public void setState(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.STATE</code>.
	 */
	public java.lang.Integer getState() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.JOURNAL.POWER</code>.
	 */
	public void setPower(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.JOURNAL.POWER</code>.
	 */
	public java.lang.Integer getPower() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.COUNTER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.intechua.db.jooq.tables.Journal.JOURNAL.POWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCounterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getPower();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value2(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value3(java.lang.Integer value) {
		setCounterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value4(java.lang.Integer value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value5(java.lang.Integer value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord value6(java.lang.Integer value) {
		setPower(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JournalRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JournalRecord
	 */
	public JournalRecord() {
		super(com.intechua.db.jooq.tables.Journal.JOURNAL);
	}

	/**
	 * Create a detached, initialised JournalRecord
	 */
	public JournalRecord(java.lang.Integer id, java.sql.Timestamp date, java.lang.Integer counterId, java.lang.Integer level, java.lang.Integer state, java.lang.Integer power) {
		super(com.intechua.db.jooq.tables.Journal.JOURNAL);

		setValue(0, id);
		setValue(1, date);
		setValue(2, counterId);
		setValue(3, level);
		setValue(4, state);
		setValue(5, power);
	}
}
