/**
 * This class is generated by jOOQ
 */
package com.intechua.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PacketsRecord extends org.jooq.impl.UpdatableRecordImpl<com.intechua.db.jooq.tables.records.PacketsRecord> implements org.jooq.Record13<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1163776222;

	/**
	 * Setter for <code>PUBLIC.PACKETS.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.DATE</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.DATE</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.MODEMID</code>.
	 */
	public void setModemid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.MODEMID</code>.
	 */
	public java.lang.Integer getModemid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.LEVEL1</code>.
	 */
	public void setLevel1(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.LEVEL1</code>.
	 */
	public java.lang.Integer getLevel1() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.LEVEL2</code>.
	 */
	public void setLevel2(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.LEVEL2</code>.
	 */
	public java.lang.Integer getLevel2() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.LEVEL3</code>.
	 */
	public void setLevel3(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.LEVEL3</code>.
	 */
	public java.lang.Integer getLevel3() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.RAWLEVEL1</code>.
	 */
	public void setRawlevel1(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.RAWLEVEL1</code>.
	 */
	public java.lang.Integer getRawlevel1() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.RAWLEVEL2</code>.
	 */
	public void setRawlevel2(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.RAWLEVEL2</code>.
	 */
	public java.lang.Integer getRawlevel2() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.RAWLEVEL3</code>.
	 */
	public void setRawlevel3(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.RAWLEVEL3</code>.
	 */
	public java.lang.Integer getRawlevel3() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.STATE</code>.
	 */
	public void setState(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.STATE</code>.
	 */
	public java.lang.Integer getState() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.CONNECTION_LEVEL</code>.
	 */
	public void setConnectionLevel(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.CONNECTION_LEVEL</code>.
	 */
	public java.lang.Integer getConnectionLevel() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.POWER</code>.
	 */
	public void setPower(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.POWER</code>.
	 */
	public java.lang.Integer getPower() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.PACKETS.B1</code>.
	 */
	public void setB1(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.PACKETS.B1</code>.
	 */
	public java.lang.String getB1() {
		return (java.lang.String) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.MODEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.LEVEL1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.LEVEL2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.LEVEL3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.RAWLEVEL1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.RAWLEVEL2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.RAWLEVEL3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.CONNECTION_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.POWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.intechua.db.jooq.tables.Packets.PACKETS.B1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getModemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getLevel1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getLevel2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getLevel3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getRawlevel1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getRawlevel2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getRawlevel3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getConnectionLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getPower();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getB1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value2(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value3(java.lang.Integer value) {
		setModemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value4(java.lang.Integer value) {
		setLevel1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value5(java.lang.Integer value) {
		setLevel2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value6(java.lang.Integer value) {
		setLevel3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value7(java.lang.Integer value) {
		setRawlevel1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value8(java.lang.Integer value) {
		setRawlevel2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value9(java.lang.Integer value) {
		setRawlevel3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value10(java.lang.Integer value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value11(java.lang.Integer value) {
		setConnectionLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value12(java.lang.Integer value) {
		setPower(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord value13(java.lang.String value) {
		setB1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PacketsRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Integer value12, java.lang.String value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PacketsRecord
	 */
	public PacketsRecord() {
		super(com.intechua.db.jooq.tables.Packets.PACKETS);
	}

	/**
	 * Create a detached, initialised PacketsRecord
	 */
	public PacketsRecord(java.lang.Integer id, java.sql.Timestamp date, java.lang.Integer modemid, java.lang.Integer level1, java.lang.Integer level2, java.lang.Integer level3, java.lang.Integer rawlevel1, java.lang.Integer rawlevel2, java.lang.Integer rawlevel3, java.lang.Integer state, java.lang.Integer connectionLevel, java.lang.Integer power, java.lang.String b1) {
		super(com.intechua.db.jooq.tables.Packets.PACKETS);

		setValue(0, id);
		setValue(1, date);
		setValue(2, modemid);
		setValue(3, level1);
		setValue(4, level2);
		setValue(5, level3);
		setValue(6, rawlevel1);
		setValue(7, rawlevel2);
		setValue(8, rawlevel3);
		setValue(9, state);
		setValue(10, connectionLevel);
		setValue(11, power);
		setValue(12, b1);
	}
}
